export default [
// Turn 1
  {
    id: 'apian-jet-coot',
    type: 'monster',
    turn: 1,
    attack: 2,
    defense: 2,
    traits: [],
  },
  {
    id: 'murderous-pixyish-neontetra',
    type: 'monster',
    turn: 1,
    attack: 1,
    defense: 1,
    traits: ['quick'],
  },
  {
    id: 'queenlike-fruitarian-blackcrappie',
    type: 'monster',
    turn: 1,
    attack: 1,
    defense: 1,
    traits: ['splash'],
  },
  {
    id: 'craniological-unworldly-argentinehornedfrog',
    type: 'monster',
    turn: 1,
    attack: 2,
    defense: 1,
    traits: ['tank'],
  },
  {
    id: 'unconstant-rainbow-eskimodog',
    type: 'monster',
    turn: 1,
    attack: 1,
    defense: 1,
    traits: ['shield'],
  },
  {
    id: 'verified-unoutlawed-ichidna',
    type: 'monster',
    turn: 1,
    attack: 2,
    defense: 1,
    traits: ['double tap'],
  },
// Turn 2
  {
    id: 'changeful-durational-rhesusmonkey',
    type: 'monster',
    turn: 2,
    attack: 2,
    defense: 3,
    traits: [],
  },
  {
    id: 'powerful-forbidden-chicken',
    type: 'monster',
    turn: 2,
    attack: 3,
    defense: 2,
    traits: [],
  },
  {
    id: 'chipper-patronizing-cougar',
    type: 'monster',
    turn: 2,
    attack: 2,
    defense: 1,
    traits: ['quick'],
  },
  {
    id: 'uncolourable-cubic-muntjac',
    type: 'monster',
    turn: 2,
    attack: 1,
    defense: 2,
    traits: ['splash'],
  },
  {
    id: 'verymad-shortish-stickleback',
    type: 'monster',
    turn: 2,
    attack: 1,
    defense: 3,
    traits: ['tank'],
  },
  {
    id: 'gluteal-complicated-grizzlybear',
    type: 'monster',
    turn: 2,
    attack: 2,
    defense: 2,
    traits: ['shield'],
  },
  {
    id: 'unbecoming-quasidepressed-arcticseal',
    type: 'monster',
    turn: 2,
    attack: 3,
    defense: 1,
    traits: ['double tap'],
  },
// Turn 3
  {
    id: 'leisured-antediluvian-hogget',
    type: 'monster',
    turn: 3,
    attack: 4,
    defense: 3,
    traits: [],
  },
  {
    id: 'semiparalyzed-charterable-pig',
    type: 'monster',
    turn: 3,
    attack: 3,
    defense: 4,
    traits: [],
  },
  {
    id: 'entomologic-homespun-earthworm',
    type: 'monster',
    turn: 3,
    attack: 3,
    defense: 2,
    traits: ['quick'],
  },
  {
    id: 'cork-pyrophobic-newt',
    type: 'monster',
    turn: 3,
    attack: 2,
    defense: 2,
    traits: ['splash'],
  },
  {
    id: 'flannel-extinct-malamute',
    type: 'monster',
    turn: 3,
    attack: 3,
    defense: 3,
    traits: ['tank'],
  },
  {
    id: 'snippy-humoursome-ant',
    type: 'monster',
    turn: 3,
    attack: 3,
    defense: 2,
    traits: ['shield'],
  },
  {
    id: 'dispossessed-growable-peafowl',
    type: 'monster',
    turn: 3,
    attack: 3,
    defense: 2,
    traits: ['double tap'],
  },
// Turn 4
  {
    id: 'censorable-raptorial-needlefish',
    type: 'monster',
    turn: 4,
    attack: 4,
    defense: 5,
    traits: [],
  },
  {
    id: 'grandiloquent-impassioned-chameleon',
    type: 'monster',
    turn: 4,
    attack: 5,
    defense: 4,
    traits: [],
  },
  {
    id: 'communicatory-bratty-cockatiel',
    type: 'monster',
    turn: 4,
    attack: 3,
    defense: 5,
    traits: ['quick'],
  },
  {
    id: 'needy-pentagonal-monkey',
    type: 'monster',
    turn: 4,
    attack: 2,
    defense: 4,
    traits: ['splash'],
  },
  {
    id: 'sufficient-consecutive-amurstarfish',
    type: 'monster',
    turn: 4,
    attack: 3,
    defense: 5,
    traits: ['tank'],
  },
  {
    id: 'nude-intraspinal-hanumanmonkey',
    type: 'monster',
    turn: 4,
    attack: 5,
    defense: 3,
    traits: ['shield'],
  },
  {
    id: 'expected-nonmetallic-oriole',
    type: 'monster',
    turn: 4,
    attack: 4,
    defense: 2,
    traits: ['double tap'],
  },
// Turn 5
  {
    id: 'eastern-polkadotted-urva',
    type: 'monster',
    turn: 5,
    attack: 6,
    defense: 6,
    traits: [],
  },
  {
    id: 'creative-undelighting-dwarfmongoose',
    type: 'monster',
    turn: 5,
    attack: 6,
    defense: 3,
    traits: ['quick'],
  },
  {
    id: 'featheredged-rusted-shelduck',
    type: 'monster',
    turn: 5,
    attack: 3,
    defense: 5,
    traits: ['splash'],
  },
  {
    id: 'depositional-adobe-argali',
    type: 'monster',
    turn: 5,
    attack: 3,
    defense: 7,
    traits: ['tank'],
  },
  {
    id: 'culinary-houndish-anemone',
    type: 'monster',
    turn: 5,
    attack: 6,
    defense: 3,
    traits: ['shield'],
  },
  {
    id: 'inconvenient-front-dassierat',
    type: 'monster',
    turn: 5,
    attack: 6,
    defense: 2,
    traits: ['double tap'],
  },
]
